### ISSUE TITLE
about space before -- 

### ISSUE THREAD

**Issue by LiXizhi** [LiXizhi/NPL#13]
The default comment command will generate following comment code

```lua
--function FuncExpression:CompileCode(ast)
     --return {ast:tostring()}
--end
```

which will be formated to 
```lua
--function FuncExpression:CompileCode(ast)
--return {ast:tostring()}
--end
```

this makes decomment difficult.  how about ignore all spaces before `--`?

same is true, such as 
```
local a;      -- this is a
```

**Comment by DarrenGZY** [comment]
need some time think about this

**Comment by DarrenGZY** [comment]
`--function FuncExpression:CompileCode(ast)
     --return {ast:tostring()}
--end`
