### ISSUE TITLE
Formatter ignore code in [[]] --[[]] and ""

### ISSUE THREAD

**Issue by LiXizhi** [LiXizhi/NPL#5]
Case1: 
```lua
--[[ 
2017-1-1 
]] 
local str = [[
2017-1-1
]]
```

will be wrongly formatted to 
```lua
--[[ 
2017 - 1 - 1 
]] 
local str = [[
2017 - 1 - 1
]]
```

Case2:

```
def("activate", p1){
    NPL.this(function()
		local +{params(p1)} = msg;
		+{emit()}
	end);
}
```
will be wrongly formatted to 
```
def("activate", p1){
    NPL.this(function()
    local +{params(p1)} = msg;
    +{emit()}
end);
}
```

**Comment by DarrenGZY** [comment]
every line in def will have the same indentation

Case1:    
`def("activate", p1){
    NPL.this(function()
		local +{params(p1)} = msg;
		+{emit()}
	end);
}`

will be formatted into

`def("activate", p1){
    NPL.this(function()
    local +{params(p1)} = msg;
    +{emit()}
    end);
}`

Case2:
`def("activate", p){
	if true then
		print()
	else
		print()
	end
}`

will be formatted into

`def("activate", p){
    if true then
    print()
    else
    print()
    end
}`
